# Generated by Django 5.2.6 on 2025-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(default='', upload_to='questions/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='plagiarism_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
