# Generated by Django 5.2.6 on 2025-09-06 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignment_question_file_assignment_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(blank=True, related_name='joined_classrooms', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.classroom'),
            preserve_default=False,
        ),
    ]
