# Generated by Django 5.2.6 on 2025-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assignment_question_file_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regdno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
